// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { Admin } from "./tables/Admin.sol";
import { Contribution } from "./tables/Contribution.sol";
import { ForceFieldDamage } from "./tables/ForceFieldDamage.sol";
import { ForceField } from "./tables/ForceField.sol";
import { BlueprintChunk } from "./tables/BlueprintChunk.sol";
