// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { Admin } from "./tables/Admin.sol";
import { BlueprintContribution } from "./tables/BlueprintContribution.sol";
import { ForceFieldDamage } from "./tables/ForceFieldDamage.sol";
import { EnergyContribution } from "./tables/EnergyContribution.sol";
import { ForceField } from "./tables/ForceField.sol";
import { BlueprintChunk } from "./tables/BlueprintChunk.sol";
import { SpawnCount } from "./tables/SpawnCount.sol";
import { SpawnEnergyConsumed } from "./tables/SpawnEnergyConsumed.sol";
